// Generated by scripts/build-icon-font.py — do not edit by hand.
// Phosphor (MIT) glyph code points for the shared icon subset.
export const GLYPHS = Object.freeze({
  "house": "\u{e2c2}",
  "pencil-simple-line": "\u{ebc6}",
  "book-open-text": "\u{e8f2}",
  "user": "\u{e4c2}",
  "play": "\u{e3d0}",
  "target": "\u{e47c}",
  "chart-bar": "\u{e150}",
  "caret-right": "\u{e13a}",
  "lightbulb": "\u{e2dc}",
  "chart-line": "\u{e154}",
});
