#!/usr/bin/env python3
"""Subset the Phosphor (MIT) regular icon font to the glyphs the shared pages
use, and embed it as base64 in app/components/icon/icon-font.css.

The current h5/ loads the whole font from node_modules at runtime. A Mini
Program cannot load a local font file, so the shared shell ships this small
subset inside its own stylesheet (no runtime request, same glyphs on H5 and
WeChat). Re-run after changing GLYPHS:

  python3 -m pip install fonttools   # once
  python3 scripts/build-icon-font.py
"""
import base64
import io
import json
import pathlib
import re

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = pathlib.Path(__file__).resolve().parent.parent
PKG = ROOT / "node_modules/@phosphor-icons/web"
SRC = PKG / "src/regular/Phosphor.ttf"
CSS = PKG / "src/regular/style.css"
OUT = ROOT / "app/components/icon/icon-font.css"
NAMES_OUT = ROOT / "app/components/icon/glyphs.js"

# Same names as h5/app.js uses on the migrated pages and the bottom entries.
GLYPHS = [
    "house", "pencil-simple-line", "book-open-text", "user",  # bottom entries
    "play", "target", "chart-bar", "caret-right",              # home cards
    "lightbulb",                                              # wrong: 小提示
    "chart-line",                                             # end: 看看最近练得怎么样
    "arrow-left", "printer", "plus",                          # back pills, print, 也看看其他练过的题
    "circle-half", "puzzle-piece", "cube", "text-superscript", "x-square",  # v0.4 domain tiles
    "lightbulb-filament", "notebook", "play-circle",          # 专项练习 placeholders 概念 / 例题 / 动画
    "grid-four", "dots-nine", "equals",                       # fallback glyphs of the v0.3 domain tiles
]

css = CSS.read_text()
codes = {}
for name in GLYPHS:
    m = re.search(r"\.ph\.ph-%s:before\s*\{\s*content:\s*\"\\([0-9a-f]+)\"" % re.escape(name), css)
    if not m:
        raise SystemExit(f"glyph {name} not found")
    codes[name] = int(m.group(1), 16)

opts = subset.Options()
opts.layout_features = []
opts.name_IDs = ["*"]
opts.notdef_outline = False
opts.flavor = None
font = TTFont(SRC)
sub = subset.Subsetter(opts)
sub.populate(unicodes=list(codes.values()))
sub.subset(font)
buf = io.BytesIO()
font.save(buf)
b64 = base64.b64encode(buf.getvalue()).decode()
version = json.loads((PKG / "package.json").read_text())["version"]

OUT.write_text(
    "/* Generated by scripts/build-icon-font.py — do not edit by hand.\n"
    f" * Subset of Phosphor Icons {version} (regular), MIT License,\n"
    " * https://github.com/phosphor-icons/web . Glyphs: " + ", ".join(GLYPHS) + ".\n"
    " */\n"
    "@font-face {\n"
    "  font-family: \"nsl-icons\";\n"
    f"  src: url(\"data:font/truetype;charset=utf-8;base64,{b64}\") format(\"truetype\");\n"
    "  font-weight: normal;\n  font-style: normal;\n  font-display: block;\n}\n"
    ".icon {\n  font-family: \"nsl-icons\" !important;\n  font-style: normal;\n  font-weight: normal;\n"
    "  line-height: 1;\n  speak: never;\n  -webkit-font-smoothing: antialiased;\n}\n"
)
NAMES_OUT.write_text(
    "// Generated by scripts/build-icon-font.py — do not edit by hand.\n"
    "// Phosphor (MIT) glyph code points for the shared icon subset.\n"
    "export const GLYPHS = Object.freeze({\n"
    + "".join(f'  "{n}": "\\u{{{c:x}}}",\n' for n, c in codes.items())
    + "});\n"
)
print(f"{OUT.relative_to(ROOT)}: {len(buf.getvalue())} bytes font, {len(GLYPHS)} glyphs")
